### ISSUE TITLE
Validations

### ISSUE THREAD

**Issue by alanwillms** [waterlink/active_record.cr#12]
Do you have any plans for implementing validations (some kind of `ActiveModel`)?

Copying @codcore (maybe you also have some thoughts on this to share)

**Comment by waterlink** [comment]
As a separated library very well might be in the future :)

Is there any points against such separation?

**Comment by alanwillms** [comment]
I may have models that _are not_ active records, so it is a good idea.

Do you know if there is anybody working on such a feature?

If there is no one, I can give it a shot :wink:

**Comment by waterlink** [comment]
I am not working on this currently (way more stuff to do here before validations) and not aware if anybody already doing something like that. According to this: http://crystalshards.herokuapp.com/ - there is no such thing yet.

**Comment by alanwillms** [comment]
Well, I will work on it adapting from Rails' ActiveModel here: https://github.com/alanwillms/active_model.cr

I will keep in touch!

**Comment by alanwillms** [comment]
@waterlink I just pushed a basic first version of it:

``` ruby
require "active_model"

class Person
  include ActiveModel

  validates [:name, :age] { presence: true }

  def initialize(@name, @age)
  end
end

person = Person.new
person.valid? # false
person.errors.messages # {:name => ["\"name\" can't be blank"], :age => ["\"age\" can't be blank"]}

person.name = "Alan"
person.age = 26
person.valid? # true

person.attributes # {:name => "Alan", :age => 26}
```

Now I have a lot of work to do: add other validators, allow custom validators, i18n of error messages, etc., but I think it won't take too long.

Take a look at the repo: https://github.com/alanwillms/active_model.cr
