### ISSUE TITLE
Connection Pool for Concurrency

### ISSUE THREAD

**Issue by sdogruyol** [waterlink/active_record.cr#40]
Currently `active_record.cr` doesn't use a Connection Pool and that's why can't handle the requests concurrently.

This leads to exceptions like

`Exception: another command is already in progress`

In `kemal-pg` i've used https://github.com/ysbaddaden/pool which is generic and can be used easily.

WDYT @waterlink ?

**Comment by waterlink** [comment]
I like it. Will play around with it and integrate in.

**Comment by sdogruyol** [comment]
That's great to hear! It's actually pretty simple to integrate you can check this for example

https://github.com/sdogruyol/kemal-pg/blob/master/src/kemal-pg.cr#L23-L25
