### ISSUE TITLE
unexpected token: ::

### ISSUE THREAD

**Issue by fridgerator** [waterlink/active_record.cr#43]
```
Syntax error in ./libs/active_record/sql/query_generator.cr:15: unexpected token: ::

      @params :: Hash(String, ::ActiveRecord::SupportedType)
```

I'm new to crystal, but shouldn't the declaration on line 15 only contain one colon separating the variable and the type?

`@params : Hash(String, ::ActiveRecord::SupportedType)`

active record version 0.3.0
crystal version 0.13.0

**Comment by waterlink** [comment]
Oh that is leftover from the old Crystal version. Could you make a PR with the fix?

**Comment by fridgerator** [comment]
It appears the fix has been made in `master` branch, just not in the `0.3.0` release.  I should have looked there first.

**Comment by waterlink** [comment]
@fridgerator I see. I made a `0.3.1` release with latest changes.
