### ISSUE TITLE
Errors using latest crystal

### ISSUE THREAD

**Issue by teodor-pripoae** [waterlink/active_record.cr#52]
I'm having a few errors when using latest crystal (0.17.4).

```

require "active_record"
^

in ./libs/active_record/active_record.cr:1: while requiring "./registry"

require "./registry"
^

in ./libs/active_record/registry.cr:1: while requiring "./adapter"

require "./adapter"
^

in ./libs/active_record/adapter.cr:1: while requiring "./types"

require "./types"
^

Syntax error in ./libs/active_record/types.cr:6: expecting token 'CONST', not '='

    {% as = "#{group.id}Types".id unless as %}
```

**Comment by Obversity** [comment]
Same here.

**Comment by waterlink** [comment]
@teodor-pripoae @Obversity I have released version `0.4.2`, it should work with Crystal `0.18.4`

**Comment by akitaonrails** [comment]
I'm obviously doing something stupid and missing something but when I try to require version 0.4.2 in my shards.yml or even the master branch I keep getting this:

```
Error resolving active_record (*, 0.4.1)
```

I tried deleting both libs/ and .shards/ folder and the lock file and starting from scratch but it keeps failing with the same error above. Tips?

**Comment by waterlink** [comment]
Oh, there is a chance that the adapter has to be updated. Which one do you use?

**Comment by akitaonrails** [comment]
Ahh, true, it's `postgres_adapter` and I am pointing to master as well.

**Comment by waterlink** [comment]
Maybe you could send a pull request to postgres adapter? I could help along the way and support you if you will have any questions about it :)

And open issue on respective repository would be awesome!

**Comment by akitaonrails** [comment]
Of course, will do :-)

**Comment by akitaonrails** [comment]
I think that with [this PR](https://github.com/waterlink/active_record.cr/pull/54) and [this PR to the pg adapter](https://github.com/waterlink/postgres_adapter.cr/pull/8), they should work again. 

@waterlink what do you think?

**Comment by fridgerator** [comment]
this seems to be resolved now?

**Comment by waterlink** [comment]
I think so  :)
